<div class="row">
    <div class="col-12">
        <h1>Agregar tarea</h1>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <form action="<?= APP_URL . "categorias/agregar"; ?>" method="post">
            <input type="hidden" name="id" value="">
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input type="text" name="nombre" id="nombre" class="form-control">
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>