<div class="row">
    <div class="col-12">
        <h1>Editar categoria</h1>
    </div>
</div>
<?php $tarea = $this->categoria ?>
<div class="row">
    <div class="col-12">
        <form action="<?= APP_URL."categorias/editar"; ?>" method="post">
            <input type="hidden" name="id" value="<?= $tarea['id']; ?>">
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input type="text" name="nombre" id="nombre" value="<?= $tarea['nombre']; ?>" class="form-control">
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>