<div class="row">
    <div class="col-12">
        <h1>Editar tarea</h1>
    </div>
</div>
<?php $tarea = $this->tarea ?>
<div class="row">
    <div class="col-12">
        <form action="<?= APP_URL . "tareas/editar"; ?>" method="post">
            <input type="hidden" name="id" value="<?= $tarea['id'] ?>">
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input type="text" name="nombre" id="nombre" class="form-control" value="<?= $tarea['nombre']; ?>">
            </div>
            <div class="form-group">
                <label for="descripcion">Descripcion</label>
                <textarea name="descripcion" id="descripcion" class="form-control"><?= $tarea['descripcion']; ?></textarea>
            </div>
            <div class="form-group">
                <label for="fecha">Fecha</label>
                <input type="date" name="fecha" id="fecha" value="<?= $tarea['fecha']; ?>" class="form-control">
            </div>
            <div class="form-group">
                <label for="prioridad">Prioridad</label>
                <input type="range" name="prioridad" id="prioridad" min="0" max="10" class="form-control"  value="<?= $tarea['prioridad']; ?>">
            </div>
            <div class="form-group">
                <label for="categoria">Categoria</label>
                <select name="categoria_id" id="categoria" class="form-control">
                    <?php foreach ($this->categorias as $categoria): ?>
                        <option value="<?= $categoria["id"] ?>" <?= $categoria['id'] === $tarea['categoria_id'] ? 'selected' : ''?>><?= $categoria["nombre"] ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>
